# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='photo',
            field=models.ImageField(default=4, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='brand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='start.Brand'),
        ),
    ]
