# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-27 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='logo',
            field=models.ImageField(blank=True, upload_to='coffeeshop_log'),
        ),
    ]
